version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DATASOURCE_HOST: mysqldb
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 31102012
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 31102012